services:
  vault:
    image: hashicorp/vault:1.16.3
    privileged: true
    command: server
    ports:
      - "8200:8200"
    cap_add:
     - IPC_LOCK
    environment:
      - VAULT_USER=${VAULT_USER}
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      # - VAULT_API_ADDR=http://0.0.0.0:8200
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
      - VAULT_USER=${VAULT_USER}
      - VAULT_PASSWORD=${VAULT_PASSWORD}
      - TEST_USER=${TEST_USER}
      - TEST_PASSWORD=${TEST_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/initdb/:/docker-entrypoint-initdb.d/
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "vault", "-U", "vault"]
      interval: 10s
      timeout: 2s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:8.7
    ports:
      - "5050:5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=rig@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_DISABLE_POSTFIX=true
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_CONFIG_PASSWORD_LENGTH_MIN=5
      - PGADMIN_CONFIG_LOGIN_BANNER="Unauthorised use is strictly forbidden."
      - PGADMIN_CONFIG_JSON_LOGGER=True
      - PGADMIN_CONFIG_LOG_ROTATION_SIZE=10 #MBs
      - PGADMIN_CONFIG_LOG_ROTATION_MAX_LOG_FILES=90
      - PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME=20
      - PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD=True
      # for now enable 2fa untill we have oauth2 or ldap
      # - PGADMIN_CONFIG_MFA_ENABLED=True
      # - PGADMIN_CONFIG_MFA_FORCE_REGISTRATION=True
      # - PGADMIN_CONFIG_MFA_SUPPORTED_METHODS=["authenticator"]
    restart: always
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin:
