#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $KEYCLOAK_USER WITH PASSWORD '$KEYCLOAK_PASSWORD';
	CREATE DATABASE keycloak;
	GRANT ALL PRIVILEGES ON DATABASE keycloak TO $KEYCLOAK_USER;
  GRANT USAGE ON SCHEMA public TO $KEYCLOAK_USER;
  GRANT CREATE ON SCHEMA public TO $KEYCLOAK_USER;
EOSQL
