apiVersion: v1
kind: Service
metadata:
  name: test-service-c8372f6e
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-k8s
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-c84c12f6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - image: paulbouwer/hello-kubernetes:latest
          name: hello-kubernetes
          ports:
            - containerPort: 8080
